///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UploadMediaModelDataFiles {
/*
{
  "extension": "png",
  "format": "image",
  "name": "1630f53fe402d71661948926rlzwmzj5zlafjp0s2tmd.png",
  "size": 135050,
  "size2": "131.88 KB",
  "type": "image/png",
  "uploaded": true,
  "replaced": false
}
*/

  String? extension;
  String? format;
  String? name;
  int? size;
  String? size2;
  String? type;
  bool? uploaded;
  bool? replaced;

  UploadMediaModelDataFiles({
    this.extension,
    this.format,
    this.name,
    this.size,
    this.size2,
    this.type,
    this.uploaded,
    this.replaced,
  });
  UploadMediaModelDataFiles.fromJson(Map<String, dynamic> json) {
    extension = json['extension']?.toString();
    format = json['format']?.toString();
    name = json['name']?.toString();
    size = json['size']?.toInt();
    size2 = json['size2']?.toString();
    type = json['type']?.toString();
    uploaded = json['uploaded'];
    replaced = json['replaced'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['extension'] = extension;
    data['format'] = format;
    data['name'] = name;
    data['size'] = size;
    data['size2'] = size2;
    data['type'] = type;
    data['uploaded'] = uploaded;
    data['replaced'] = replaced;
    return data;
  }
}

class UploadMediaModelData {
/*
{
  "hasWarnings": false,
  "isSuccess": true,
  "warnings": [
    ""
  ],
  "files": [
    {
      "extension": "png",
      "format": "image",
      "name": "1630f53fe402d71661948926rlzwmzj5zlafjp0s2tmd.png",
      "size": 135050,
      "size2": "131.88 KB",
      "type": "image/png",
      "uploaded": true,
      "replaced": false
    }
  ]
}
*/

  bool? hasWarnings;
  bool? isSuccess;
  List<String?>? warnings;
  List<UploadMediaModelDataFiles?>? files;

  UploadMediaModelData({
    this.hasWarnings,
    this.isSuccess,
    this.warnings,
    this.files,
  });
  UploadMediaModelData.fromJson(Map<String, dynamic> json) {
    hasWarnings = json['hasWarnings'];
    isSuccess = json['isSuccess'];
    if (json['warnings'] != null) {
      final v = json['warnings'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      warnings = arr0;
    }
    if (json['files'] != null) {
      final v = json['files'];
      final arr0 = <UploadMediaModelDataFiles>[];
      v.forEach((v) {
        arr0.add(UploadMediaModelDataFiles.fromJson(v));
      });
      files = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['hasWarnings'] = hasWarnings;
    data['isSuccess'] = isSuccess;
    if (warnings != null) {
      final v = warnings;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['warnings'] = arr0;
    }
    if (files != null) {
      final v = files;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['files'] = arr0;
    }
    return data;
  }
}

class UploadMediaModel {
/*
{
  "data": {
    "hasWarnings": false,
    "isSuccess": true,
    "warnings": [
      ""
    ],
    "files": [
      {
        "extension": "png",
        "format": "image",
        "name": "1630f53fe402d71661948926rlzwmzj5zlafjp0s2tmd.png",
        "size": 135050,
        "size2": "131.88 KB",
        "type": "image/png",
        "uploaded": true,
        "replaced": false
      }
    ]
  },
  "message": "Action successful.",
  "success": true,
  "status_code": 200
}
*/

  UploadMediaModelData? data;
  String? message;
  bool? success;
  int? statusCode;

  UploadMediaModel({
    this.data,
    this.message,
    this.success,
    this.statusCode,
  });
  UploadMediaModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? UploadMediaModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    success = json['success'];
    statusCode = json['status_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['success'] = success;
    data['status_code'] = statusCode;
    return data;
  }
}
