///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "token": "07CfMKAIyLFgwiAXLlGyEpv2PT69T0TDzewmIThrsuZogbhS2YJypspF1UtD",
  "username": "Admin ",
  "email": "admin@example.com",
  "assigned": "2022-07-07T04:39:46.051258Z",
  "expires": "2022-08-06T14:39:46.051266Z"
}
*/

  String? token;
  String? username;
  String? email;
  String? assigned;
  String? expires;

  LoginModel({
    this.token,
    this.username,
    this.email,
    this.assigned,
    this.expires,
  });

  LoginModel.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    username = json['username']?.toString();
    email = json['email']?.toString();
    assigned = json['assigned']?.toString();
    expires = json['expires']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['username'] = username;
    data['email'] = email;
    data['assigned'] = assigned;
    data['expires'] = expires;
    return data;
  }
}